# -*- coding: utf-8 -*-
"""helper_functions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ub5nkpTsodlrUj4aGM-SUgDgiwCoiynv
"""

import tensorflow as tf

tf.__version__

# Create function to unzip a zipfile into current working directory 
# (since we're going to be downloading and unzipping a few files)

import zipfile

def unzip_data(filename):
  zip_ref = zipfile.ZipFile(filename, 'r')
  zip_ref.extractall()
  zip_ref.close()

# Walk through an image classification directory and find out how many files (images)
# are in each subdirectory.

import os

def walk_through_dir(dir_path):
  for dirpath, dirnames, filenames in os.Walk(dir_path):
    print(f"there are {len(dirnames)} directories and {len(filenames)} filenames in {dirpath}")